service: api

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DYNAMO_SCORE_TABLE: scores
    DYNAMO_USER_TABLE: users

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:PutItem
        - dynamodb:ListStreams
        - dynamodb:DescribeStream
      Resource: "arn:aws:dynamodb:${self:provider.region}:*"

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMO_USER_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: name
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: name
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ScoresTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.DYNAMO_SCORE_TABLE}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

functions:
  create-score:
    handler: handler.scoreCreate
    events:
      - http:
          path: score
          method: post
          cors: true
  ranking-trigger:
    handler: handler.rankingHandler
    events:
      - stream:
          type: dynamodb
          arn:
            Fn::GetAtt:
              - ScoresTable
              - StreamArn
